services:
  - type: web
    name: escola-strapi
    env: node
    plan: free
    region: ohio
    rootDir: backend
    # COMANDO QUE LIMPA TUDO ANTES DE INSTALAR
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --legacy-peer-deps --no-audit --no-fund
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3000
    healthCheckPath: /_health
    autoDeploy: true
